// SPDX-License-Identifier: MPL-2.0
// Derived from https://github.com/museumsvictoria/nodel at revision 19756071383d696682688ab436c77c0a1f80c783.
import {
  actionAttrs,
  actionEventJoinPointRule,
  attr,
  confirmAttrs,
  eventPointRule,
  ignoredClass,
  meterShowPointRule,
  partialClass,
  propagatesClass,
  sourceRef,
  showAttrs,
  statusShowPointRule,
  unsupportedClass,
  V1_NODEL_BUILTIN_TYPES,
  type V1UiComponent,
} from "./shared.js";

export const V1_CONTENT_COMPONENTS = [
  {
    name: "title",
    category: "content",
    summary: "Heading text, defaulting to h4, optionally bound to an event.",
    attributes: [attr("size", "heading level", { default: "4" }), attr("event", "point name"), ...showAttrs],
    allowedChildren: { allowed: ["text content only"] },
    variants: [
      {
        name: "size",
        when: "size is present",
        markup: ["Generates h<size> instead of h4."],
      },
    ],
    markup: {
      outerTag: "h4 or hN",
      outerClasses: ["sect"],
      dataAttributes: ["data-event", "data-showevent", "data-showarg", "data-showeventarg"],
      significantDescendants: [],
      notes: ["When showevent is present, class is exactly sect; XML class is not appended."],
    },
    classPropagation: unsupportedClass,
    pointRules: [eventPointRule, statusShowPointRule],
    valueBehavior: ["String/number event values replace heading text."],
    css: ["Uses normal heading styles."],
    sourceRefs: [
      sourceRef("templates.xsl", "186-225"),
      sourceRef("nodel.js", "3348-3349"),
      sourceRef("nodel.js", "3422-3423"),
    ],
  },
  {
    name: "subtitle",
    category: "content",
    summary: "Heading text, defaulting to h5, optionally bound to an event.",
    attributes: [attr("size", "heading level", { default: "5" }), attr("event", "point name"), ...showAttrs],
    allowedChildren: { allowed: ["text content only"] },
    variants: [
      {
        name: "size",
        when: "size is present",
        markup: ["Generates h<size> instead of h5."],
      },
    ],
    markup: {
      outerTag: "h5 or hN",
      outerClasses: ["sect"],
      dataAttributes: ["data-event", "data-showevent", "data-showarg", "data-showeventarg"],
      significantDescendants: [],
      notes: ["Shares the title_body template with title."],
    },
    classPropagation: unsupportedClass,
    pointRules: [eventPointRule, statusShowPointRule],
    valueBehavior: ["String/number event values replace heading text."],
    css: ["Uses normal heading styles."],
    sourceRefs: [
      sourceRef("templates.xsl", "186-239"),
      sourceRef("nodel.js", "3348-3349"),
      sourceRef("nodel.js", "3422-3423"),
    ],
  },
  {
    name: "text",
    category: "content",
    summary: "Paragraph text with optional leading icon and event-driven value updates.",
    attributes: [attr("event", "point name"), ...showAttrs],
    allowedChildren: { allowed: ["icon", "text content"] },
    variants: [],
    markup: {
      outerTag: "p",
      outerClasses: ["sect"],
      dataAttributes: ["data-event", "data-showevent", "data-showarg", "data-showeventarg"],
      significantDescendants: ["optional icon span"],
      notes: ["XML class is not appended; showevent class is sect only."],
    },
    classPropagation: unsupportedClass,
    pointRules: [eventPointRule, statusShowPointRule],
    valueBehavior: ["String/number event values replace paragraph text."],
    css: ["Uses normal paragraph styles."],
    sourceRefs: [
      sourceRef("templates.xsl", "242-270"),
      sourceRef("nodel.js", "3348-3349"),
      sourceRef("nodel.js", "3422-3423"),
    ],
  },
  {
    name: "icon",
    category: "content",
    summary: "Static icon span using Bootstrap glyphicons by default or Font Awesome when lib='fa'.",
    attributes: [
      attr("type", "icon name", { required: true }),
      attr("lib", "icon library", {
        values: ["fa"],
        notes: ["Absent means Bootstrap glyphicon."],
      }),
      attr("style", "Font Awesome style class", { default: "fas" }),
      attr("size", "Font Awesome multiplier", {
        notes: ["Generates fa-<size>x for Font Awesome only."],
      }),
    ],
    allowedChildren: { allowed: [] },
    variants: [
      {
        name: "glyphicon",
        when: "lib is absent",
        markup: ["span.glyphicon.glyphicon-<type>."],
      },
      {
        name: "font-awesome",
        when: "lib='fa'",
        markup: ["span.<style>.fa-<type> plus optional fa-<size>x."],
      },
    ],
    markup: {
      outerTag: "span",
      outerClasses: ["glyphicon", "glyphicon-*", "fas", "fa-*"],
      dataAttributes: [],
      significantDescendants: [],
      notes: ["Only lib='fa' is handled specially; other lib values emit nothing."],
    },
    classPropagation: unsupportedClass,
    pointRules: [],
    valueBehavior: ["Static icon only."],
    css: ["Depends on bundled Bootstrap glyphicons and Font Awesome classes."],
    sourceRefs: [sourceRef("templates.xsl", "442-474")],
  },
  {
    name: "image",
    category: "content",
    summary: "Responsive image that can update its src from an event.",
    attributes: [
      attr("source", "browser path", { required: true }),
      attr("event", "point name"),
      attr("height", "pixels"),
      attr("width", "pixels"),
      ...showAttrs,
    ],
    allowedChildren: { allowed: [] },
    variants: [],
    markup: {
      outerTag: "img",
      outerClasses: ["img-responsive", "sect"],
      dataAttributes: ["data-event", "data-showevent", "data-showarg", "data-showeventarg"],
      significantDescendants: [],
      notes: ["height/width generate max-height/max-width inline styles in pixels."],
    },
    classPropagation: unsupportedClass,
    pointRules: [eventPointRule, statusShowPointRule],
    valueBehavior: ["String event values replace the img src attribute."],
    css: ["Always gets img-responsive; optional max-height/max-width inline CSS."],
    sourceRefs: [sourceRef("templates.xsl", "477-521"), sourceRef("nodel.js", "3431-3434")],
  },
  {
    name: "link",
    category: "content",
    summary: "Button-style link to a node, URL, or the remote node bound to a parent status event.",
    attributes: [attr("node", "node name"), attr("url", "URL"), ...showAttrs],
    allowedChildren: { allowed: ["text content"] },
    variants: [
      {
        name: "node",
        when: "node is present and url is absent",
        markup: ["a.btn.btn-outline data-link-node."],
      },
      {
        name: "url",
        when: "url is present and node is absent",
        markup: ["a.btn.btn-outline data-link-url."],
      },
      {
        name: "parent-event",
        when: "neither url nor node is present",
        markup: ["a.btn.btn-outline data-link-event from parent @event."],
      },
    ],
    markup: {
      outerTag: "a",
      outerClasses: ["btn", "btn-outline", "sect"],
      dataAttributes: [
        "data-link-node",
        "data-link-url",
        "data-link-event",
        "data-showevent",
        "data-showarg",
        "data-showeventarg",
      ],
      significantDescendants: ["span.glyphicon-new-window", "span label"],
      notes: ["Click handlers open a new window or discover a remote binding target."],
    },
    classPropagation: unsupportedClass,
    pointRules: [
      {
        xmlAttributes: ["node", "url", "parent event"],
        generatedDataAttributes: ["data-link-node", "data-link-url", "data-link-event"],
        references: ["remote"],
        notes: ["No local action is called; link behavior is browser navigation/discovery."],
      },
      statusShowPointRule,
    ],
    valueBehavior: [
      "Static link target except parent-event variant, which reads REST/remote for the parent event binding target.",
    ],
    css: ["btn-outline has a translucent border and spacing for label spans."],
    sourceRefs: [
      sourceRef("templates.xsl", "1183-1260"),
      sourceRef("theme.less", "230-235"),
      sourceRef("nodel.js", "1485-1521"),
    ],
  },
] as const satisfies readonly V1UiComponent[];
