// SPDX-License-Identifier: MPL-2.0
// Derived from https://github.com/museumsvictoria/nodel at revision 19756071383d696682688ab436c77c0a1f80c783.
import {
  actionAttrs,
  actionEventJoinPointRule,
  attr,
  confirmAttrs,
  eventPointRule,
  ignoredClass,
  meterShowPointRule,
  partialClass,
  propagatesClass,
  sourceRef,
  showAttrs,
  statusShowPointRule,
  unsupportedClass,
  V1_NODEL_BUILTIN_TYPES,
  type V1UiComponent,
} from "./shared.js";

export const V1_STATE_COMPONENTS = [
  {
    name: "status",
    category: "state",
    summary: "Panel-style status display, optionally with embedded controls and child status displays.",
    attributes: [
      attr("event", "point name"),
      attr("page", "page title", {
        notes: ["Generates data-nav to navigate to a page when clicked."],
      }),
      ...showAttrs,
      attr("class", "CSS classes", {
        notes: ["Ignored by the current transform."],
      }),
    ],
    allowedChildren: {
      allowed: [
        "image",
        "icon",
        "link",
        "button",
        "switch",
        "partialswitch",
        "badge",
        "partialbadge",
        "signal",
        "statussleep",
        "text content",
      ],
    },
    variants: [],
    markup: {
      outerTag: "div",
      outerClasses: ["panel", "panel-default", "statusgroup", "clearfix", "sect"],
      dataAttributes: ["data-status", "data-nav", "data-showevent", "data-showarg", "data-showeventarg"],
      significantDescendants: ["div.panel-body", "span.status", "optional statussleep footer"],
      notes: ["status uses data-status rather than data-event for panel severity updates."],
    },
    classPropagation: unsupportedClass,
    pointRules: [
      {
        xmlAttributes: ["event"],
        generatedDataAttributes: ["data-status"],
        references: ["status"],
        notes: ["Status processing listens to local event activity but applies panel/label severity classes."],
      },
      statusShowPointRule,
    ],
    valueBehavior: [
      "Boolean event values toggle default/success. Objects with numeric level map 0 success, 1 warning, 2-4 danger, 5 primary/info-like; string message updates the displayed status text.",
    ],
    css: ["Bootstrap panel classes; child buttons/labels have special styling under panel-primary in theme.less."],
    sourceRefs: [
      sourceRef("templates.xsl", "1079-1122"),
      sourceRef("nodel.js", "3460-3493"),
      sourceRef("theme.less", "141"),
    ],
  },
  {
    name: "statussleep",
    category: "state",
    summary: "Status panel footer with a fixed danger Sleep action button.",
    attributes: [attr("action", "point name", { required: true }), ...showAttrs],
    allowedChildren: { allowed: [] },
    variants: [],
    markup: {
      outerTag: "div",
      outerClasses: ["panel-footer", "clearfix", "sect"],
      dataAttributes: ["data-showevent", "data-showarg", "data-showeventarg", "data-action"],
      significantDescendants: ["a.btn.btn-danger labelled Sleep"],
      notes: ["Only emitted when nested in a status with event."],
    },
    classPropagation: unsupportedClass,
    pointRules: [
      {
        xmlAttributes: ["action"],
        generatedDataAttributes: ["data-action"],
        references: ["action"],
        notes: ["Click calls the named local action with an empty JSON object."],
      },
      statusShowPointRule,
    ],
    valueBehavior: ["Click calls action; no arg is generated."],
    css: ["Bootstrap panel-footer and btn-danger."],
    sourceRefs: [sourceRef("templates.xsl", "1125-1144")],
  },
  {
    name: "badge",
    category: "state",
    summary: "Label-style status display suitable inside buttons, pills, and status panels.",
    attributes: [attr("event", "point name"), attr("type", "extra CSS class")],
    allowedChildren: { allowed: ["text content"] },
    variants: [],
    markup: {
      outerTag: "span",
      outerClasses: ["label", "label-default", "status"],
      dataAttributes: ["data-status"],
      significantDescendants: [],
      notes: ["type is appended as a CSS class after label label-default status."],
    },
    classPropagation: unsupportedClass,
    pointRules: [
      {
        xmlAttributes: ["event"],
        generatedDataAttributes: ["data-status"],
        references: ["status"],
        notes: ["Uses status processing like status panels, but with label-* classes."],
      },
    ],
    valueBehavior: ["Boolean and object status values update label classes and message text."],
    css: ["Empty status labels display a non-breaking space via theme.less."],
    sourceRefs: [
      sourceRef("templates.xsl", "1146-1161"),
      sourceRef("nodel.js", "3460-3493"),
      sourceRef("theme.less", "299-304"),
    ],
  },
  {
    name: "partialbadge",
    category: "state",
    summary: "Label-style partial state display for Off/On/PartiallyOff/PartiallyOn strings.",
    attributes: [
      attr("event", "point name"),
      attr("off", "label", { default: "Off" }),
      attr("on", "label", { default: "On" }),
    ],
    allowedChildren: { allowed: ["text content"] },
    variants: [],
    markup: {
      outerTag: "span",
      outerClasses: ["label", "label-default", "label-pbadge"],
      dataAttributes: ["data-event", "data-class-off", "data-class-on", "data-off", "data-on"],
      significantDescendants: [],
      notes: ["class-off/class-on are fixed to label-danger/label-success by the template."],
    },
    classPropagation: unsupportedClass,
    pointRules: [eventPointRule],
    valueBehavior: [
      "Event strings Off/On/PartiallyOff/PartiallyOn update text and label-danger/label-success/label-warning classes.",
    ],
    css: ["Bootstrap label classes; partial state uses label-warning."],
    sourceRefs: [sourceRef("templates.xsl", "1164-1180"), sourceRef("nodel.js", "3380-3399")],
  },
  {
    name: "panel",
    category: "state",
    summary: "Scrollable markdown-rendered panel bound to a text event.",
    attributes: [
      attr("event", "point name", { required: true }),
      attr("height", "pixels", { required: true }),
      attr("value", "jQuery-decoded scalar", {
        notes: ["Alias for showvalue on visibility."],
      }),
      ...showAttrs,
    ],
    allowedChildren: { allowed: [] },
    variants: [],
    markup: {
      outerTag: "div",
      outerClasses: ["panel", "panel-default", "panel<body height>px", "scrollbar-inner", "sect"],
      dataAttributes: ["data-event", "data-showevent", "data-showarg", "data-showeventarg"],
      significantDescendants: ["div.panel-body", "div.scrollbar-inner", "inline style for height"],
      notes: ["Height is embedded in a generated class name and inline style block."],
    },
    classPropagation: unsupportedClass,
    pointRules: [eventPointRule, statusShowPointRule],
    valueBehavior: [
      "String event values are converted from Markdown to HTML and inserted into the scrollbar-inner div.",
    ],
    css: ["Generated .panel<height>px style sets fixed height and overflow hidden."],
    sourceRefs: [sourceRef("templates.xsl", "1263-1299"), sourceRef("nodel.js", "3400-3402")],
  },
  {
    name: "field",
    category: "state",
    summary: "Read-only form input showing the latest event value.",
    attributes: [attr("event", "point name", { required: true })],
    allowedChildren: { allowed: [] },
    variants: [],
    markup: {
      outerTag: "div/form/input",
      outerClasses: ["form-control"],
      dataAttributes: ["data-event", "data-arg-source"],
      significantDescendants: ["input.form-control[readonly]"],
      notes: ["Generated input is readonly and data-arg-source='this'."],
    },
    classPropagation: unsupportedClass,
    pointRules: [eventPointRule],
    valueBehavior: ["String/number/boolean event values update the input value unless active."],
    css: ["Bootstrap form-control."],
    sourceRefs: [
      sourceRef("templates.xsl", "1488-1490"),
      sourceRef("nodel.js", "3431-3434"),
      sourceRef("nodel.js", "3452-3455"),
    ],
  },
  {
    name: "qrcode",
    category: "state",
    summary: "QR code card from static text or an event-driven string.",
    attributes: [
      attr("event", "point name"),
      attr("text", "text"),
      attr("height", "pixels", { default: "128" }),
      attr("help", "text"),
    ],
    allowedChildren: { allowed: [] },
    variants: [],
    markup: {
      outerTag: "div",
      outerClasses: ["qrcode-card", "qrcode-wrapper", "qrcode", "qrcode-help"],
      dataAttributes: ["data-event", "data-text", "data-height", "data-help"],
      significantDescendants: ["div.qrcode", "optional help paragraph"],
      notes: ["When event is present, id is qrcode-<event>."],
    },
    classPropagation: unsupportedClass,
    pointRules: [eventPointRule],
    valueBehavior: ["Initial QR code uses text. String event values clear and remake the QR code."],
    css: ["QR code width is set to height + 4 pixels by nodel.js."],
    sourceRefs: [
      sourceRef("templates.xsl", "1534-1570"),
      sourceRef("nodel.js", "3076-3111"),
      sourceRef("nodel.js", "3415-3420"),
    ],
  },
  {
    name: "meter",
    category: "state",
    summary: "Numeric meter bar with vertical default orientation and optional horizontal orientation.",
    attributes: [
      attr("event", "point name"),
      attr("type", "variant", { values: ["horizontal"] }),
      attr("range", "scale", { values: ["perc", "db"], default: "perc" }),
      attr("class", "CSS classes", {
        notes: ["Ignored by the current transform."],
      }),
      attr("showevent", "point name"),
      attr("showvalue", "jQuery-decoded scalar or JSON array"),
    ],
    allowedChildren: { allowed: [] },
    variants: [
      {
        name: "vertical",
        when: "type absent or not horizontal",
        markup: ["div.meter[data-type] with nested base/bar divs and p numeric label."],
        css: ["Default meter is vertical."],
      },
      {
        name: "horizontal",
        when: "type='horizontal'",
        markup: ["Same DOM with data-type='horizontal'."],
        css: [
          "Rotates the bar, sets width to meter height, margin-right:40px, and positions p at right:-35px top:5px.",
        ],
      },
    ],
    markup: {
      outerTag: "div",
      outerClasses: ["meter", "sect"],
      dataAttributes: ["data-event", "data-type", "data-range", "data-showevent", "data-showarg"],
      significantDescendants: [
        "div > div.base.label-default",
        "div.bar > label-danger/warning/success divs",
        "p numeric label initialized to 0",
      ],
      notes: ["The numeric p is always generated after the nested bar divs."],
    },
    classPropagation: ignoredClass("outer div.meter"),
    pointRules: [eventPointRule, meterShowPointRule],
    valueBehavior: [
      "Numeric event values update bar clip and floor(value) into p. range='db' scales display percentage as 88*Math.pow(10,value/40).",
    ],
    css: [
      "Default vertical dimensions use meter variables. Horizontal meters set margin-right:40px and position p at right:-35px.",
    ],
    sourceRefs: [
      sourceRef("templates.xsl", "1573-1615"),
      sourceRef("theme.less", "237-298"),
      sourceRef("nodel.js", "269-302"),
    ],
  },
  {
    name: "signal",
    category: "state",
    summary: "Compact numeric signal label with meter colour classes.",
    attributes: [attr("event", "point name"), attr("range", "scale", { values: ["perc", "db"], default: "perc" })],
    allowedChildren: { allowed: ["text content"] },
    variants: [],
    markup: {
      outerTag: "span",
      outerClasses: ["label", "signal", "meter-colour-0"],
      dataAttributes: ["data-event", "data-range"],
      significantDescendants: [],
      notes: ["The initial text is the XML text content."],
    },
    classPropagation: unsupportedClass,
    pointRules: [eventPointRule],
    valueBehavior: [
      "Numeric event values update meter-colour-N class; text is otherwise updated by generic span handling.",
    ],
    css: [
      "meter-colour-0..100 classes are generated from success/warning/danger color ramps. Empty signal labels display a non-breaking space.",
    ],
    sourceRefs: [
      sourceRef("templates.xsl", "1618-1628"),
      sourceRef("theme.less", "299-328"),
      sourceRef("nodel.js", "304-313"),
    ],
  },
] as const satisfies readonly V1UiComponent[];
