import {
  V1_UI_AUTHORITATIVE_SOURCES,
  V1_UI_CATALOG_METADATA,
  V1_UI_COMPONENT_INDEX,
  V1_UI_CSS_RECIPES,
  V1_UI_SOURCE_REVISION,
  decodeV1DataAttribute,
  getV1ClassPropagationSummary,
} from "./v1UiCatalog.js";

const CLASS_PROPAGATION = getV1ClassPropagationSummary();

const formatDecodedDataAttribute = (source: string) => {
  const decoded = decodeV1DataAttribute(source);
  const type = decoded === null ? "null" : Array.isArray(decoded) ? "array" : typeof decoded;
  const rendered = typeof decoded === "string" ? `"${decoded}"` : JSON.stringify(decoded);
  return `${source} -> ${rendered} (${type})`;
};

const DATA_ATTRIBUTE_EXAMPLES = [
  "true",
  "false",
  "null",
  "0",
  "1",
  "0.5",
  "05",
  "1.0",
  '["HDMI 1","USB-C"]',
  '{"key":"203","value":"Input 1"}',
].map(formatDecodedDataAttribute);

const COMPONENT_INDEX_LINES = V1_UI_COMPONENT_INDEX.map((component) => `- ${component.name}: ${component.summary}`);

export const V1_XML_UI_GUIDELINES = [
  "# Nodel V1 XML UI Guidelines",
  "",
  "## Scope and authority",
  "- This derived guidance incorporates source facts from museumsvictoria/nodel revision " +
    V1_UI_SOURCE_REVISION +
    ", licensed under MPL-2.0. It is maintained independently and does not imply upstream endorsement.",
  "- This guide covers the legacy v1 XML/XSLT dashboard format only. It is the compatibility path for XML custom UI files, not the v2 HTML custom-element authoring model.",
  "- Prefer the existing node's dashboard style when editing an established recipe. Preserve public action, signal/event, and binding names unless the operator explicitly approves a breaking change.",
  `- Treat the installed runtime behavior and pinned v1 sources as authoritative. Catalog facts in this build are pinned to museumsvictoria/nodel revision ${V1_UI_SOURCE_REVISION}.`,
  "- Use the shared v1 UI catalog for exact component markup, data attributes, class propagation, point generation, value behavior, CSS notes, and source anchors.",
  "- Do not rely on index.xsd as a complete schema. It is useful historical context, but it is incomplete relative to current templates.xsl and nodel.js behavior.",
  "",
  "## Three behavior layers",
  "1. XML/XSLT/browser behavior: index.xsl and templates.xsl transform XML into HTML, data-* attributes, built-in CSS classes, and browser-side nodel.js behavior.",
  "2. Live registered Nodel actions/signals and schemas: the current node must actually expose the local actions and events referenced by the generated browser data attributes.",
  "3. Standard Frontend recipe parser behavior: some Frontend recipes parse content/index.xml to register points, but that parser is a separate layer with its own limits and schemas.",
  "",
  "## Files and transformation",
  "- Store the default node dashboard as content/index.xml. Nodel serves the content/ folder as the node web root, so browsers request it as index.xml or /nodes/<NodeName>/index.xml, not content/index.xml.",
  "- Additional simple-named dashboards can be stored as content/<name>.xml and opened as <name>.xml from the node web root. Keep names simple because the v1 picker discovers content/\\w+.(xml|html|htm).",
  '- A v1 XML dashboard should begin with the processing instruction <?xml-stylesheet type="text/xsl" href="v1/index.xsl"?> so the browser applies the built-in stylesheet.',
  "- The root element is pages. It may set title, css, js, theme, logo, and core. The css and js paths are browser-facing content-root paths such as css/custom.css or js/custom.js; do not include the content/ prefix.",
  "- Authors write XML attributes such as action, event, join, showevent, data, and arg. The XSLT generates HTML attributes such as data-action, data-event, data-render, data-showevent, data-arg-action, and data-arg. Do not hand-author data-action, data-event, or other generated data-* attributes in v1 XML.",
  "- Query strings are safe and useful for cache-busting browser-facing CSS, JS, logo, and image paths, for example css/custom.css?v=20260717. File matching tools should strip query/hash before checking content/ assets.",
  "",
  "## Canonical starter",
  "~~~xml",
  '<?xml version="1.0" encoding="UTF-8"?>',
  '<?xml-stylesheet type="text/xsl" href="v1/index.xsl"?>',
  '<pages title="Room Control" css="css/custom.css?v=20260717" js="js/custom.js?v=20260717">',
  '  <page title="Main">',
  '    <row class="main-controls">',
  '      <column sm="4">',
  "        <title>Power</title>",
  '        <switch join="Power" confirm="true"/>',
  "      </column>",
  '      <column sm="4">',
  "        <title>Source</title>",
  "        <buttongroup>",
  '          <button action="SetSource" event="Source" arg="HDMI 1">HDMI 1</button>',
  '          <button action="SetSource" event="Source" arg="USB-C">USB-C</button>',
  "        </buttongroup>",
  "      </column>",
  '      <column sm="4">',
  "        <title>Status</title>",
  '        <status event="DeviceStatus">Device state</status>',
  "      </column>",
  "    </row>",
  "  </page>",
  "</pages>",
  "~~~",
  "",
  "## Component index",
  ...COMPONENT_INDEX_LINES,
  "",
  "## Actions, events, joins, and arguments",
  '- action="Name" creates a UI command path to the current node action named Name. The v1 runtime calls relative REST/actions/<Name>/call.',
  '- event="Name" subscribes the generated control to current-node activity for the local signal/event named Name. The v1 runtime updates controls from WebSocket activity or REST/activity polling.',
  '- join="Name" is shorthand for using the same current-node point name as both action and event where the control supports both directions. join takes precedence over simultaneous action/event attributes in the current templates.',
  "- Names in action, event, join, data, and showevent must match local current-node actions and signals/events after the recipe loads. Inspect them with nodel.get_node_actions and nodel.get_node_signals before authoring or changing a dashboard.",
  "- Remote equipment should be mediated by the recipe. Browser controls call local current-node actions and consume local current-node signals/events; the recipe then uses RemoteAction bindings, remote event handlers, or other toolkit helpers to talk to target nodes/devices.",
  '- arg supplies an action argument. The generated call body is JSON with an arg member, for example {"arg":"HDMI 1"}. Keep action schemas aligned with what the browser actually sends after jQuery data coercion.',
  '- arg-on and arg-off make a normal button toggle between two argument values based on its active class. action-on and action-off on button type="momentary" send different actions for press and release.',
  '- A button action may be a JSON array string such as ["Action1","Action2"] when multiple current-node actions should be called from one click. Use this sparingly and keep the behavior obvious to operators.',
  "- Selection controls send the chosen item or pill value as arg. Switch sends booleans. Partial switch sends Off or On strings and displays partial state strings. Range explicitly sends numbers through data-arg-type='number'.",
  "",
  "## Browser data coercion and strict matching",
  "- v1 runtime code reads generated data-* attributes through jQuery .data(), not raw strings. Exact true, false, and null become booleans/null; canonical numeric strings become numbers; valid JSON arrays/objects become arrays/objects; other values stay strings.",
  "- Canonical numeric means the string round-trips through Number(value).toString(). Values such as 05 and 1.0 stay strings, while 1 and 0.5 become numbers.",
  "- Button arg, arg-on, and arg-off use that jQuery-decoded value unless the element also has data-arg-type. Ordinary buttons do not set data-arg-type; range inputs set data-arg-type='number' and parseFloat the current slider value.",
  "- Event activation compares event values to decoded data-arg values with strict equality through $.inArray. A recipe emitting number 1 will not activate a button whose arg is the string 1.0.",
  "- showvalue and arrays in generated data-showarg are also jQuery-decoded. Keep showvalue types aligned with emitted event values.",
  ...DATA_ATTRIBUTE_EXAMPLES.map((example) => `- Data decode example: ${example}.`),
  "",
  "## Button and switch state",
  "- Normal button class-on defaults to btn-primary. When the button has action/event/join, templates emit data-class-on even if class-on is absent.",
  "- Normal button class defaults to btn btn-default. If XML class is present, the generated class becomes btn <class> plus optional sect/haschild, so include any desired Bootstrap color class yourself.",
  "- Button event matching removes data-class-on and re-adds it only when the incoming event value strictly matches data-arg. arg-on/arg-off choose the outgoing arg based on whether the button currently has data-class-on.",
  "- switch defaults to class-off btn-danger and class-on btn-success. Its child data-arg values are false and true, decoded as booleans.",
  "- partialswitch sends Off/On strings and displays Off, On, PartiallyOff, and PartiallyOn after lowercasing and removing non-letter characters.",
  "",
  "## Dynamic selectors",
  "- dynamicselect and dynamicbuttongroup use the XML data attribute as a local event name. The XSLT generates data-render and the browser renders the latest event arg through JsRender templates.",
  '- The dynamic event arg should be an array of objects shaped like {"value":"Input 1"} or {"key":"203","value":"Input 1"}. key is the action argument when present; value is the visible label.',
  "- Do not rely on scalar arrays for dynamic selectors. The current templates read value and optional key properties and scalar entries produce blank or unusable choices.",
  "- Very large dynamic arrays produce large dropdowns/button groups without virtualization. Keep lists bounded or add custom UI code deliberately.",
  "",
  "## Meters, ranges, and numeric displays",
  "- meter transforms to .meter[data-type] containing nested bar divs and a numeric p initialized to 0. XML class on meter is ignored.",
  '- Meters are vertical by default. meter type="horizontal" uses the same DOM, rotates the bar in CSS, sets margin-right: 40px, and positions the numeric p at top: 5px and right: -35px.',
  '- meter and signal support range="perc" and range="db". range="db" scales the visual percentage while the displayed number remains floor(event value).',
  '- range min, max, and step affect the browser slider. step defaults to 1. nudge adds plus/minus buttons and type="vertical" rotates the control with generated height classes.',
  '- range type="mute" adds a companion button. It appends Muting to the base join/action/event names for the mute action and mute event references, and sends booleans through arg-on/arg-off.',
  "",
  "## Class propagation and CSS scoping",
  `- XML class propagates on: ${CLASS_PROPAGATION.propagates.join(", ")}.`,
  `- XML class partially propagates on: ${CLASS_PROPAGATION.partial.join(", ")}. For select and dynamicselect it is applied to the trigger button, not the outer btn-select wrapper.`,
  `- Common elements whose XML class is ignored by the current transform include: ${CLASS_PROPAGATION.ignored.join(", ")}.`,
  "- page always generates div.container-fluid.page. column generates Bootstrap col-* classes. group generates div.well. meter generates div.meter. None of those copy XML class.",
  '- Prefer row class for dashboard section scoping, for example <row class="source-section"> and CSS selectors such as .source-section .well or .source-section .meter.',
  "- For controls that propagate class, keep required Bootstrap base behavior intact. Do not remove generated data-* attributes or child data-arg values with custom scripts/CSS.",
  "",
  "## State and conditional visibility",
  "- event-bound controls update from the current-node activity stream. A UI can look empty or inactive until the recipe emits initial state after startup.",
  '- showevent="Name" conditionally shows an element when matching activity arrives. Conditional sections are hidden initially by the v1 runtime.',
  '- showvalue compares scalar event values. It can be a single value or a JSON array string, for example showvalue=\'["Off","Half"]\'. Values are jQuery-decoded before strict matching.',
  "- showeventarg extracts a nested property from an object event value before applying showvalue comparison.",
  "- Emit local events at startup and after commands complete so active buttons, switches, selects, meters, and visibility sections represent real device state rather than only recent operator clicks.",
  "",
  "## Standard Frontend parser and schemas",
  "- XML/XSLT/browser behavior is not the same as recipe parser registration. A browser reference can exist even when the recipe did not register the matching action or event.",
  "- The standard Frontend recipe parser registers action, event, join, action-on, and action-off attributes. Its current loadIndexFile path does not register dynamic-selector data events, showevent visibility events, or generated type='mute' companion points ending in Muting.",
  '- If a range uses type="mute", verify the live node exposes the derived <Base>Muting action/event or define those companion points in another loaded recipe file.',
  "- The standard parser selects schemas from content/schemas.json by XML element type, with optional <type>_action and <type>_signal overrides where that parser supports them.",
  "- XML min, max, and step affect browser controls but do not register JSON Schema minimum, maximum, or multipleOf by themselves. Define schemas in recipe point declarations or schemas.json when bounds matter to tools or runtime metadata.",
  "- Nodel executes configured nodeConfig.json dependencies, or script.py when no dependency list exists, then appends sorted ingredient*.py files and sorted custom*.py files in the same shared interpreter before extracting bindings. Parser-generated or companion points can be satisfied by those later files if they define matching names.",
  "- Treat parser observations as parser-layer findings only. Do not assert standard parser rules for a custom recipe unless it has durable fingerprints such as loadIndexFile, schemaMap, element-type schema lookup, and base action/event/join extraction.",
  "",
  "## Practical control reference",
  "- Layout and text: pages contains page and pagegroup. Pages contain row; rows contain column. Use xs, sm, md, and lg column widths on a 12-column grid. Use group for a visual well, grid/cell for dense button tables, title/subtitle/text for labels, and gap for spacing.",
  '- Buttons: button supports action, event, join, arg, arg-on, arg-off, confirm, confirmtitle, confirmtext, showevent, class, class-on, child badge/partialbadge/signal/icon/text/image, and type="momentary" with action-on/action-off. buttongroup lays out related buttons and can be vertical.',
  "- Switches: switch is a boolean Off/On control. partialswitch is a string-state Off/On control that also displays PartiallyOff and PartiallyOn from event values. Both support action/event/join, confirmation, labels, classes, and visibility attributes.",
  "- Static selection: pills/pill and select/item bind a shared action/event/join and send the selected pill or item value as arg. They update active selection from matching event values.",
  "- Dynamic selection: dynamicselect and dynamicbuttongroup render choices from the signal named by data. Payloads must be arrays of {value, key?} objects.",
  '- Ranges: range binds numeric values. Use min, max, step, nudge, type="vertical", and type="mute" as needed. type="mute" appends Muting to the action/event/join base name for the mute button.',
  "- Status display: status and badge expect either booleans or status objects. Status level 0 maps to success, 1 to warning, 2-4 to danger, and 5 to primary/info-like styling; message is shown when present. partialbadge follows partial switch strings.",
  '- Numeric display: meter and signal display numeric values and support range="perc" or range="db".',
  "- Text and long values: field displays a read-only event value. panel displays markdown-rendered long text in a scrollable panel. title, subtitle, text, and image can also bind event values where templates support it.",
  '- Media and navigation: image can use event values as image sources. icon supports Bootstrap glyphicons by default and Font Awesome with lib="fa". qrcode renders static text or an event-driven code. link supports url, node, or a parent event binding link.',
  "- Lighting: lighting binds a color picker to action/event/join and supports options flags for color channels.",
  `- Built-in nodel widgets: nodel type supports description, actsig, log, serverlog, charts, console, params, remote, list, locals, diagnostics, add, editor, toolkit, plus header-only hosticon, edit, and nav handling.`,
  "",
  "## Safety, XML correctness, and verification",
  "- XML must be well-formed. Quote attributes, escape literal ampersands as &amp;, and do not include -- inside XML comments.",
  "- Before editing, read the existing XML file, inspect current-node actions/signals, and inspect bindings if the UI is intended to control other equipment.",
  "- Use supporting-file tools for XML: nodel.get_node_files, nodel.propose_node_file_text or nodel.propose_node_file_edit, nodel.verify_write_plan, and nodel.save_node_file_text or nodel.apply_node_file_edit. Do not use recipe script tools for XML.",
  "- Supporting XML file writes use REST/files/save, do not run recipe validation, and should be verified by read-back hash/content. Do not restart the node just because an XML file changed.",
  "- Verify that every generated action/event/data/showevent reference has a live local point or a deliberate parser/recipe path that creates it. Pay special attention to type='mute' Muting companions and dynamic selector data events.",
  "- When browser access is available, open the node dashboard URL, confirm the XSLT and v1 assets load, exercise representative actions, and verify event-driven state and showevent visibility. If browser verification is unavailable, state that rendering and interaction were not verified.",
  "- If a dashboard depends on actions/events that do not exist yet, create or update the recipe first, reload and verify the recipe actions/signals, then update the XML dashboard.",
  "",
  "## CSS recipes in the shared catalog",
  ...V1_UI_CSS_RECIPES.map((recipe) => `- ${recipe.name}: ${recipe.description}`),
  "",
  "## Further references",
  `- Upstream sample: https://github.com/museumsvictoria/nodel/blob/${V1_UI_SOURCE_REVISION}/nodel-webui-js/src/index.xml`,
  `- XSLT shell: https://github.com/museumsvictoria/nodel/blob/${V1_UI_SOURCE_REVISION}/nodel-webui-js/src/index.xsl`,
  `- XSLT templates: https://github.com/museumsvictoria/nodel/blob/${V1_UI_SOURCE_REVISION}/nodel-webui-js/src/templates.xsl`,
  `- V1 runtime JavaScript: https://github.com/museumsvictoria/nodel/blob/${V1_UI_SOURCE_REVISION}/nodel-webui-js/src/nodel.js`,
  `- V1 theme CSS source: https://github.com/museumsvictoria/nodel/blob/${V1_UI_SOURCE_REVISION}/nodel-webui-js/src/theme.less`,
  "- Dashboard snippets wiki: https://github.com/museumsvictoria/nodel/wiki/Dashboard-Snippets",
  "- Public Frontend recipes and wiki snippets can contain older copied support files. Current installed runtime behavior and current source templates win on disagreement.",
].join("\n");

export function v1XmlUiGuidance() {
  return {
    format: "v1_xml_xslt",
    scope: "legacy_compatibility",
    guidelines: V1_XML_UI_GUIDELINES,
    catalogMetadata: V1_UI_CATALOG_METADATA,
    componentIndex: V1_UI_COMPONENT_INDEX,
    cssRecipes: V1_UI_CSS_RECIPES.map((recipe) => ({
      name: recipe.name,
      title: recipe.title,
      components: recipe.components,
      description: recipe.description,
    })),
    classPropagation: CLASS_PROPAGATION,
    dataAttributeDecodingExamples: DATA_ATTRIBUTE_EXAMPLES,
    authoritativeSources: V1_UI_AUTHORITATIVE_SOURCES,
    caveats: [
      "This guidance covers legacy v1 XML/XSLT dashboards only; v2 HTML custom elements are a separate authoring model.",
      "The checked-in index.xsd is incomplete and stale relative to current templates.xsl and nodel.js behavior.",
      "Current installed runtime behavior and existing local dashboard style take precedence over bundled guidance when they disagree.",
      "The standard Frontend parser is a recipe-layer convention, not the browser XSLT runtime; verify live registered points and schemas separately.",
    ],
  };
}
